index:
    path: /
    controller: App\Controller\HomeController::index

app_login:
    path: /api/login
    controller : App\Controller\Auth\LoginController:login
    methods: POST

books_index:
    path: /api/books
    controller: App\Controller\Api\BookController:index
    methods: GET

